# DE {#de}


No need to run this - load up the preprepared Seurat object.


```{r eval=FALSE}
################################################################################
# Prepare a datasets
library(Seurat)
library(SeuratData)
library(tidyverse)
data("hcabm40k") #maybe?


# grab 4000 random cells
keep_cells <- sample(1:ncol(hcabm40k), size=4000)
  
# Subsample down to a toy sized dataset
hcabm40k.mini <- hcabm40k[,keep_cells] 
# clear large object from memory
rm(hcabm40k)

# Add a group of contidion vs control to test. Not real
# This is the first 4 of 8 bio replicates
condition_lookup <- 
  c('MantonBM1'="fake_treat",   'MantonBM2'="fake_treat",   'MantonBM3'="fake_treat",   'MantonBM4'="fake_treat",
    'MantonBM5'="fake_control", 'MantonBM6'="fake_control", 'MantonBM7'="fake_control", 'MantonBM8'="fake_control")
hcabm40k.mini$condition <- condition_lookup[hcabm40k.mini@meta.data$orig.ident]



# ADDING SOME FAKE VARIATION!
# Mmultipling first 40 genes of the the 'fake treat' group by 4 - so we expect these to be DE.
# In reality, these are simply healthy replicates and shouldn't be significantly different
alter_cells <- which(condition_lookup[hcabm40k.mini$orig.ident] == "fake_treat")
alter_genes <- rownames(hcabm40k.mini@assays$RNA@counts)[1:50] 
hcabm40k.mini@assays$RNA@counts[alter_genes, alter_cells ] <- hcabm40k.mini@assays$RNA@counts[alter_genes, alter_cells  ]* 4
# Plus - add 1 to some of them too (2*0 is 0)
alter_cells2 <- sample(alter_cells, 500, replace = FALSE) # add 1 to x of 1979 cells.
hcabm40k.mini@assays$RNA@counts[alter_genes, alter_cells2 ] <- hcabm40k.mini@assays$RNA@counts[alter_genes, alter_cells2  ]* +1


# there's gene level meta data (meta.features) for each assay. 
# Recodring which values we changed.
hcabm40k.mini[['RNA']][['is_altered']] <- rownames(hcabm40k.mini[['RNA']]) %in% alter_genes



#-------------------------------------------------------------------------------
#  Run thorough a basic processing, with no QC

hcabm40k.mini <- NormalizeData(hcabm40k.mini, normalization.method = "LogNormalize", scale.factor = 10000)
hcabm40k.mini <- FindVariableFeatures(hcabm40k.mini, selection.method = "vst", nfeatures = 2000)
all.genes     <- rownames(hcabm40k.mini)
hcabm40k.mini <- ScaleData(hcabm40k.mini, features = all.genes)
hcabm40k.mini <- RunPCA(hcabm40k.mini, features = VariableFeatures(object = hcabm40k.mini))
hcabm40k.mini <- RunUMAP(hcabm40k.mini, dims = 1:10)
hcabm40k.mini <- FindNeighbors(hcabm40k.mini, dims = 1:10)
hcabm40k.mini <- FindClusters(hcabm40k.mini, resolution = 0.1) # Low res


#------------------------------------------------------------------------------
# save
saveRDS(hcabm40k.mini, file="data/hcabm40k_mini_withfakevariation.rds")


```


Load up the small (4000cell) subset of data.  The replicates have been divided in to control and test groups This is just a demo, they're all healthy controls.

```{r}
hcabm40k.mini <- readRDS(file="data/hcabm40k_mini_withfakevariation.rds")

table( hcabm40k.mini$orig.ident, hcabm40k.mini$condition)
```


```{r}
# The first 40 genes were altered.
altered_genes <- rownames(hcabm40k.mini[['RNA']])[1:50]
altered_genes
```



```{R eval=FALSE}
# When Diing DE, it makes sense to remove genes with too-low counts to find anything in.
# There's alot of these in single cell. 
total_per_gene <- rowSums(GetAssayData(hcabm40k.mini, 'counts'))
hist(log10(total_per_gene))
hcabm40k.mini <- hcabm40k.mini[total_per_gene >= 100, ]



#-------------------------------------------------------------------------------
#  The object;

p1 <- DimPlot(hcabm40k.mini, reduction = 'umap', group.by = 'seurat_clusters')
p2 <- DimPlot(hcabm40k.mini, reduction = 'umap', group.by = 'orig.ident')
p1+p2


################################################################################
# What is different between 'fake treat' and 'fake control'?
# Expect the 20 genes that we altered, but little else

#-------------------------------------------------------------------------------
# Find all markers

hcabm40k.mini.c0 <- hcabm40k.mini[, hcabm40k.mini$seurat_clusters == 0]


# Change Ident to condition
Idents(hcabm40k.mini.c0)
Idents(hcabm40k.mini.c0) <- hcabm40k.mini.c0$condition



# default, wilcox test
de_result_wilcox <- FindMarkers(hcabm40k.mini.c0, 
            ident.1 = 'fake_treat',
            ident.2 = 'fake_control',
            logfc.threshold = 0, # Give me ALL results
            min.pct = 0
            )

# the  'DE' genes
de_result_wilcox$was_altered <- rownames(de_result_wilcox ) %in% alter_genes

filter(de_result_wilcox, p_val_adj < 0.01)
filter(de_result_wilcox, was_altered == TRUE)




#-------------------------------------------------------------------------------
# Pseudobuilk

# Change idents to sample fro grouping.
levels(Idents(hcabm40k.mini.c0))
Idents(hcabm40k.mini.c0) <- hcabm40k.mini.c0$orig.ident
levels(Idents(hcabm40k.mini.c0))

pseudobulk_matrix <- AggregateExpression( hcabm40k.mini.c0,  slot = 'counts', assays='RNA' )[['RNA']]


# treat like a bulk DE
library(limma)
library(edgeR)
library(patchwork)

dge <- DGEList(pseudobulk_matrix)
dge <- calcNormFactors(dge)

condition <- factor(condition_lookup[colnames(pseudobulk_matrix)])
design <- model.matrix(~condition)
vm  <- voom(dge, design = design, plot = TRUE)
fit <- lmFit(vm, design = design)
fit <- eBayes(fit)
de_result_pseudobulk <- topTable(fit, n = Inf, adjust.method = "BH")
de_result_pseudobulk <- arrange(de_result_pseudobulk , adj.P.Val)
de_result_pseudobulk$was_altered <- rownames(de_result_pseudobulk ) %in% alter_genes



filter(de_result_pseudobulk,    adj.P.Val < 0.05)
filter(de_result_pseudobulk, was_altered == TRUE)


#-----------------------------------------------------------

p1 <- ggplot(de_result_pseudobulk, aes(x=AveExpr, y=logFC, col=adj.P.Val < 0.05)) +
  geom_point() +
  geom_point(data=filter(de_result_pseudobulk, was_altered), pch=3, col='blue', size=5 ) +
  scale_colour_manual(values=c('TRUE'="red",'FALSE'="black")) + 
  theme_bw() +
  ggtitle("Pseudobulk")

# Seurat doesn't give aveg expression by default, just grab it from the psuedobulk
de_result_wilcox$AveExpr <- de_result_pseudobulk[rownames(de_result_wilcox),c('AveExpr')]

p2 <- ggplot(de_result_wilcox, aes(x=AveExpr, y=avg_log2FC, col=p_val_adj < 0.05)) +
  geom_point() +
  geom_point(data=filter(de_result_wilcox, was_altered), pch=3, col='blue', size=5 ) +
  scale_colour_manual(values=c('TRUE'="red",'FALSE'="black")) + 
  theme_bw() +
  ggtitle("Wilcox Test")




p1 + p2

```





