---
title: "Workshop Delivery Notes"
output: html_notebook
---



---

To replace a broken pbmc object, give participant the relevant part of the code to catch them up.

```
library(dplyr)
library(ggplot2)
library(Seurat)
library(patchwork)

pbmc.data <- Read10X(data.dir = "data/pbmc3k/filtered_gene_bc_matrices/hg19/")
pbmc      <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc$percent.mt <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc, selection.method = 'vst', nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- RunUMAP(pbmc, dims = 1:10)
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
```

Or just load the finished object (includes all analysis, so warn that defaults will differ);

```
pbmc <- readRDS("data/pbmc_tutorial.rds")
```


-----



# The Seurat object

This section is to show people what we're aiming for! Else there's a whoooollle lot of processing steps before some payoff.


* Mention 'copy-paste' button!
* Everyone to load object, people can follow along doing same plots if they want to.

* Emphasise the metadata table - and that its got analysis in!



Plotting

* Defaults everywhere!
* Dim Plot = Categoricial, Feature plot = continueous
* We can plot the things in the metadata, or genes. Case matters.


* Walk through interpretation ov VlnPlot - Raw counts - many zeros!


## Activity Plotting

Demo trying to plot a mouse gene to show the error you get with wrong capitalisation. 

This breakout is to check everyone can load the data and do a plot. 


## Discussion 'The Seurat object in R'

Not covering, it is a bit too indepth for this training.
Explain that its there for referring back to, but leave it for interetsed parties!

Enocourage keen folk to discuss in breakout room.



# Load Data


Presenter to open up a real 10X data structure 'this is what you get if your seq facility runs cell ranger' - show the inputs files.

_Then_ load the Seurat demo data.

* This metadata table is almost empty!
* Explain breifly why counts are '.'


* **GREEN TICK** Everyone loaded data ok?


# QC Filtering

This section will run quite long (hopefully if there's discussionion!). The intention is to relate each step to the biology - go into 'why' we are doing them.


* Emphasise Looking at the data and choosing your own threshold!



### The meta data slot

* Suggest people add 'sample1' to a sample column, as though this was one of several samples. We won't use it though. Explain thats a common task!
* Breakout room convo suggestion; ask people what each column is? Why do we care?


### QC filtering continued...

Spend a long time going through each individual plot. And why. Ask people to identify thresholds!

* Small activity: get people to drop threhsolds in slack). I've seen people pick seurat's tutorial thresholds, which aren't going to be great for modern data!
* For the scatter plots, discuss the relations between stats => You can filter on nFeature or nCounts since they're correlated!
* Apply filtering. 
* I'd personally not set a max gene threhsold at all 
* You pick the right threholds for your data - this data is old and the tech got much better!



### Apply Filtering

* Breakout to apply filtering and see how many cells survive. ncol(pbmc)/pbmc summary e.t.c
* Try some different thresholds in a new object and disuss how many cells they get.


* **GREEN TICK** Everyone filtered data ok?



### QC filtering continued...

Then, Disscuss other information/filtering options. Not covered in Seurat tutorial, so add a slide?

This is an 'annotation phase' of the analysis.

* Ribisomal RNA
* Doublets
* low diversity
* E.g. Chicken RBCs have nuclei?
* Cell cycle ( but not for filtering.)



# Normalisation

Demo - Show counts vs norm. Explain that again this is just one normalisation method. 

* **GREEN TICK** Everyone run normalisation ok?



# PCAs and UMAPs.

Will need to talk through these steps a little. Possibly refer to some extra slides about why we need to.


* Why do we need variable genes? - There are alot of genes, most of which arnt informative.
* Why scale the data? - Don't let a handful of genes, e.g. Xist take over!
* PCA! Is this a good viz?? 
   - Actually it's not too bad. But this is PBMC data. Complex tissues will be a blob!
   - Explain the PC weightings.
   - PC plots are there for troubleshooting - do you have a sex effect on PC2, is PC1 batch effect e.t.c


   
* **GREEN TICK** Can everyone make a PCA plot? If not, get help in breakout.


### Challenge PC genes

* Mention suerat's treatment of defaults -> if not UMAP then PCA.
* FeaturePlot(pbmc_processed, features =  "CD14")

### PCAs and UMAPs continued ...


Get everyone to copy-paste the UMAP run.
   
* **GREEN TICK** Can everyone make a UMAP plot?

* That took a while - time to save object!



# Clustering

Again Refer to slides for some discussion of what 'findNeighbors' does.

Then do clustering.

* **GREEN TICK** Can everyone see clusters on UMAP plot?

### Challenge Different cluster settings

* Show and tell your cluster settings.
* Encourage people to rerun the first 10 dimensions and resolution 0.5 so they get the same object.


# Cluster Markers

* Spend some time working through the output tables.
* Explain the assumptions for marker finding. 
* Sometimse you can filter on pct.2 for non-uqbituotous - show examples.



Section Assigning cell identity to clusters: 
 * That method only works for this dataset, and this exact set of parameters!!! 
 * Demo a different way that you might do it for real, copy cluster IDs, rename them one by one in a new column.
 * Introduce reassignment of Idents() here (set back afterwards).
 

 
 
https://github.com/ellefeg/RNASeq

http://bioconductor.org/books/devel/SingleRBook/
Ming tang's list.


















